### ISSUE TITLE
modify `search_builders/concerns/iiif_print/exclude_models` to make it easy to set which models do not show up in search at a work type model level

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/iiif_print#12]
# Summary 

[exclude_models](https://github.com/scientist-softserv/iiif_print/blob/main/app/search_builders/concerns/iiif_print/exclude_models.rb) should be configurable. 

# Acceptance Criteria

- [ ] A developer should be able to exclude certain models from search within the application

# Screenshots or Video

https://drive.google.com/file/d/1b9gK-eA5wih1GDiT4PCwFRKEGWo_PC4_/view?usp=share_link

# Testing Instructions

- [ ] Add `'Image'` to the excluded work from the config
  - [ ] eg. `config.models_to_be_excluded_from_search = []` in `config\initializers\iiif_pring.rb` within your Hyku application
- [ ] Search for the Image
- [ ] Confirm it does not show up

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by ShanaLMoore** [comment]
Note: we are excluding Attachment from UTK for reference

**Comment by ShanaLMoore** [comment]
clarify implementation plan for how this should be configured by the user

**Comment by kirkkwang** [comment]
The video listed shows that this works, closing ticket.
