### ISSUE TITLE
repackage `NewspaperPageDerivativeService` to be more generic

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/iiif_print#13]
# Summary 

Currently, only `NewspaperPage` can use [NewspaperPageDerivativeService](https://github.com/scientist-softserv/iiif_print/blob/main/app/services/iiif_print/newspaper_page_derivative_service.rb#L2). 

We would like to generalize this and be able to choose which class can use the service. The class should be configurable. 

# Acceptance Criteria 

- [ ] Make [NewspaperPageDerivativeService](https://github.com/scientist-softserv/iiif_print/blob/main/app/services/iiif_print/newspaper_page_derivative_service.rb) configurable. 

# Testing Instructions

**Comment by ShanaLMoore** [comment]
Does class include module/behavior (LaRita's customization per #7 )

**Comment by kirkkwang** [comment]
I think the test coverage is acceptable, also this was reimplemented in #14.

[ref](https://github.com/scientist-softserv/iiif_print/blob/bb2855d27d799579c55a750dc86539917437df0a/lib/iiif_print/page_derivative_service.rb#L25)
