### ISSUE TITLE
Image Processing: Tiff sizing

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#130]
This ticket was created from a spike, ref: https://github.com/scientist-softserv/utk-hyku/issues/310

# Summary

There are several image processing issues. It is unclear whether these are ghostscript issues or a derivative issues.

# The problem

The tiff files that are split off are massive. A 2-page pdf of around 55 KB generated two 45 MB files, each 3400 x 4400 (probably a ghostscript configuration issue).

# Desired resolution

- [ ] Tiff files generate at a reasonable size (unsure what reasonable size is so any improvement is better)

# Screenshots

![Screenshot 2023-01-13 at 7 41 59 PM](https://user-images.githubusercontent.com/17851674/214115840-3ac1f647-744f-4c9a-a924-a90cb0643f64.png)

![Screenshot 2023-01-13 at 11 44 42 PM](https://user-images.githubusercontent.com/17851674/214113837-14649c3a-ee85-4356-a266-60f6ab37e41f.png)

# Duplicating the issue

Create a Generic Work in Hyku + IiifPrint, with a PDF file (use either UI or Bulkrax import with PDF in the same row as parent). IiifPrint will split the PDF into individual tiff files.

I was also able to upload one of the generated tiff files using bulkrax to show what it is looking like: https://demo.hyku-iiif.notch8.cloud/concern/generic_works/7caaab4c-673d-4179-8113-a85b88aba39c?locale=en

**Comment by ShanaLMoore** [comment]
PR: https://github.com/scientist-softserv/iiif_print/pull/104

**Comment by ShanaLMoore** [comment]
Due to technicalities, @kirkkwang will QA this ticket locally and attach his results to show the tiff size.

**Comment by kirkkwang** [comment]
Before:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/19597776/218194731-e7eb2c0a-0061-4fa5-837e-4e037cdecb12.png">
There wasn't any compression on the tiff which resulted in really large images

After:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/19597776/218194945-a0c0f24d-37cc-440d-8c13-32d3828d8eea.png">
Now using LZW compression

**Comment by ShanaLMoore** [comment]
Don't QA or deploy to staging until #81 gets through QA
