### ISSUE TITLE
make it easy to turn on or off derivative services at a class level

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/iiif_print#14]
# Summary 

We currently don't have a way to select what type of derivatives to make. 

ie: "for this work type, only make tiffs and not pdfs" or "don't OCR"... 

There is currently no way to turn this on and off for a given class. 

# Acceptance Criteria

- [ ] a user should be able to select what types of derivatives a work type should create

# Testing Instructions

- [ ] if a user turns a type of derivative off, the create derivatives job should not make that type of derivative for that particular work type
- [ ] Perhaps all derivative types should get created by default?
- [ ] Example scenarios to test:
### As developer

I want to create all derivatives available from IIIF Print for my `Image` work type:

```rb
# Image model
class Image < ActiveFedora::Base
  include IiifPrint.model_configuration
end
```

I want to create just TIFF derivatives:

```rb
class Image < ActiveFedora::Base
  include IiifPrint.model_configuration(
    derivative_service_plugins: [
      IiifPrint::TIFFDerivativeService
    ]
  )
end
```

I want to create all JP2, PDF, and text derivatives but not TIFF:

```rb
class Image < ActiveFedora::Base
  include IiifPrint.model_configuration(
    derivative_service_plugins: [
      IiifPrint::JP2DerivativeService,
      IiifPrint::PDFDerivativeService,
      IiifPrint::TextExtractionDerivativeService
    ]
  )
end
```
- [ ] once adjusted, deploy the application to staging and create a new `Image`
- [ ] go to the show page and down below in the items partial, see that the download options match expectations

**Comment by ShanaLMoore** [comment]
![Image](https://user-images.githubusercontent.com/10081604/207161657-de93c70d-e4e5-4ec4-b5c2-7289fdc1248c.png)

**Comment by ShanaLMoore** [comment]
@kirkkwang Could you update the testing instructions with how a user can turn it on/off, for QA purposes. 

If I recall, this is a setting that a dev would need to do?

**Comment by kirkkwang** [comment]
Yes it is something a dev needs to do.  Not sure why I closed this ticket, I think it was on of those things where the PR got merged and the ticket closed automatically??  That's strange..

**Comment by kirkkwang** [comment]
I feel there is enough in the specs to close this one
