### ISSUE TITLE
Spike: Ensure PDFs generate properly and PDF splitting occurs

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#151]
# Summary

When a PDF is trying to get created, we see the following error:

```sh
convert-im6.q16: attempt to perform an operation not allowed by the security policy 'PDF' @ error/constitute.c/IsCoderAuthorized/421.
```

This prevents PDFs from being created properly. 

# Acceptance Criteria

- [x] PDFs can be downloaded and opened from the download drop down in the items partial
- [x] PDF splitting occurs as intended by IIIF Print

# Screenshots or Video

# Testing Instructions

- [x] Upload a PDF as an `Image`
- [x] Ensure the PDF splitting happens
- [ ] #222 (failed QA so we've created a separate bug ticket to resolve and focus on scope) 

# Notes

The `im6` hints at perhaps an ImageMagick versioning issue.  IIIF Print was developed with Hyku on ImageMagick v7.1.0-57 which solved a specific tiff offset bug

ref: https://github.com/samvera/hyku/commit/85f4d605e8af4a26a24dd0a1292058dcedfbec86

**Comment by jillpe** [comment]
Should be solved by #150

**Comment by ShanaLMoore** [comment]
blocked until client gives us a staging to deploy to

**Comment by ShanaLMoore** [comment]
To test, you will need an IU account that has been registered with a [VPN](https://playbook-staging.notch8.com/en/projects/essi). Your account will need admin access as well cc the essi client channel or ping Kirk/Shana. 

After logging into VPN, you'll be able to access the following site. 

Test site:  https://dcadmin-test.dlib.indiana.edu/

**Comment by kirkkwang** [comment]
tested on https://dcadmin-test.dlib.indiana.edu/ (staging) and got this error:

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/19597776/230436568-63810a45-5af6-4dbe-8b4d-66befc0cfb4a.png">

**Comment by ShanaLMoore** [comment]
## retest without selecting a rights statement:

**Comment by ShanaLMoore** [comment]
Actually, the client has confirmed that they don't want PDF splitting to happen. I will close this and the spin off ticket we created.
