### ISSUE TITLE
Spike: OCR text is not work properly, the `txt`, `json`, and `xml` do get created but with no text

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#152]
# Summary

OCR is either not getting generated or not getting saved to the `txt`, `json`, and `xml` derivatives.  Without proper OCR data, `all_text_tsimv` does not get populated and catalog search also does not work.  UV OCR search does not work either.

# Acceptance Criteria

- [x] `txt`, `json`, and `xml` derivatives have OCR text when looking at a work that has text
- [x] the FileSet's `all_text_tsimv` gets populated with OCR text
- [x] searching OCR'd words in UV finds and highlights the text in the viewer

# Screenshots or Video

# Testing Instructions

- [ ] create an image that has text
- [ ] download the `txt`, `json`, and `xml` files and observe that they have the OCR'd text data
- [ ] search for a word in UV and observe that the viewer jumps to the word and highlights it

# Notes

**Comment by jillpe** [comment]
Should be solved by #150

**Comment by ShanaLMoore** [comment]
blocked until client gives us a staging to deploy to

**Comment by ShanaLMoore** [comment]
To test, you will need an IU account that has been registered with a [VPN](https://playbook-staging.notch8.com/en/projects/essi). Your account will need admin access as well cc the essi client channel or ping Kirk/Shana. 

After logging into VPN, you'll be able to access the following site. 

Test site:  https://dcadmin-test.dlib.indiana.edu/

**Comment by kirkkwang** [comment]
Showing up correctly locally 🤔 


![Image](https://user-images.githubusercontent.com/19597776/232546953-6c176d14-e56b-40f4-aa33-dc388dec2246.png)

**Comment by ShanaLMoore** [comment]
Closing this ticket per the dev meeting discussion. We will not be using iiif print's OCR processes. ref: https://docs.google.com/document/d/16s4x6rWcxK5Npwf9OmjUK5EAYssit_TeAHiTYzlMAk0/edit#heading=h.lflqqhz56xtl
