### ISSUE TITLE
Metadata pane should change when clicking through different works

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#153]
# Summary

Currently, the metadata pane only shows the parent's metadata and does not change when clicking on a child work.

# Acceptance Criteria

- [x] when clicking on a child work, the child work's metadata is shown

# Screenshots or Video

# Testing Instructions

- [ ] create a parent and child work with some metadata
- [ ] observe that the parent metadata shows when viewed
- [ ] observe that the child metadata shows when viewed

# Notes

**Comment by jillpe** [comment]
"Individual child/member work metadata can be viewed in the “more information” tab, which currently only shows a subset of metadata. The initial requirement is for all publicly viewable (exposed) metadata to appear in the viewer. If display becomes too crowded, Indiana can add a tag to metadata they would like to appear in the viewer."

**Comment by ShanaLMoore** [comment]
blocked until client gives us a staging to deploy to

**Comment by ShanaLMoore** [comment]
To test, you will need an IU account that has been registered with a [VPN](https://playbook-staging.notch8.com/en/projects/essi). Your account will need admin access as well cc the essi client channel or ping Kirk/Shana. 

After logging into VPN, you'll be able to access the following site. 

Test site:  https://dcadmin-test.dlib.indiana.edu/

**Comment by kirkkwang** [comment]
Metadata is changing when clicking on a new work:

![metadata-pane-essi](https://user-images.githubusercontent.com/19597776/230452576-fe6a9b73-1025-4351-b041-18fa56c3ef18.gif)
