### ISSUE TITLE
Spike: IiifPrint + Bulkrax Exporter

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#162]
Generally test how exporter works, when iiif_print is installed. 

How does iiif_print change bulkrax's export behavior, if at all?

BL had a bunch of questions about what to expect , which may determine feature requests they'll want/need. 

When you export a pdf split work, does it export all of the children too? 
If so, is it possible to export a parent or is_page_of column that'll link it back to its parent?

**Comment by DeonFranklin** [comment]
Export complete with failures

![Image](https://user-images.githubusercontent.com/95306716/227601627-d52d36e0-521b-40df-8035-5bdaa88aeb72.png)


Stack trace: https://mola.bl-staging.notch8.cloud/exporters/9/entries/264?locale=en

![Image](https://user-images.githubusercontent.com/95306716/227601754-0b9b63ac-5a43-4384-bc62-4fadb41cd7be.png)

**Comment by ShanaLMoore** [comment]
I retested this today with #289 See the results [here](https://github.com/scientist-softserv/britishlibrary/issues/289#issuecomment-1485626124). 

We [imported](https://qa.bl-staging.notch8.cloud/importers/1?locale=en) a Book work type for pdf split. When we [exported](https://qa.bl-staging.notch8.cloud/exporters/2?locale=en) it, it included the file_sets and and the csv includes the parent/child columns to show the relationships. 


[export_2_5_1.zip](https://github.com/scientist-softserv/iiif_print/files/11082005/export_2_5_1.zip)
