### ISSUE TITLE
Naming convention not working as intended for expected sorting

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#167]
# Summary

Title sorting behaves undesirably after nine items.

Ex:
```rb
titles = ["Foo Pdf Nbr 1, Page 1",
          "Foo Pdf Nbr 1, Page 2",
          "Foo Pdf Nbr 1, Page 3",
          "Foo Pdf Nbr 1, Page 4",
          "Foo Pdf Nbr 1, Page 5",
          "Foo Pdf Nbr 1, Page 6",
          "Foo Pdf Nbr 1, Page 7",
          "Foo Pdf Nbr 1, Page 8",
          "Foo Pdf Nbr 1, Page 9",
          "Foo Pdf Nbr 1, Page 10"]
```
```rb
titles.sort 
#=> ["Foo Pdf Nbr 1, Page 1",
#    "Foo Pdf Nbr 1, Page 10", # undesirable order
#    "Foo Pdf Nbr 1, Page 2",
#    "Foo Pdf Nbr 1, Page 3",
#    "Foo Pdf Nbr 1, Page 4",
#    "Foo Pdf Nbr 1, Page 5",
#    "Foo Pdf Nbr 1, Page 6",
#    "Foo Pdf Nbr 1, Page 7",
#    "Foo Pdf Nbr 1, Page 8",
#    "Foo Pdf Nbr 1, Page 9"]
```
# Acceptance Criteria

- [ ] Titles should sort in an expected manner where 10 does not come after 1

# Screenshots or Video

# Testing Instructions

- [ ] Ingest this [Sample PDF](https://github.com/scientist-softserv/iiif_print/files/10916922/service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf)
- [ ] observe that the titles go in a predictable order

# Notes

Padding the numbers with zeros can be a solution.

**Comment by ShanaLMoore** [comment]
blocked until client gives us a staging to deploy to

**Comment by DiemBTran** [comment]
**Needs further review:** It looks like a 20-page document has been running its derivatives for 3 hours. This may be unusual behavior.

tested on:
- https://mola.bl-staging.notch8.cloud/concern/articles/531123c9-daa2-4c1f-a0d1-dd7502899d31?locale=en
- [service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf](https://github.com/scientist-softserv/iiif_print/files/11084430/service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf)


<details><summary>20-page PDF still has its derivatives being run. Its children works are being made, but they have not been attached to the parent.</summary>

![Article naming convention ID 531123c9-daa2-4c1f-a0d1-dd7502899d31 Hyku 2023-03-27 at 5 17 38 PM](https://user-images.githubusercontent.com/29311858/228106943-673d016a-050a-4f01-b922-193f920e05ee.jpg)
![Sidekiq 2023-03-27 at 5 18 05 PM](https://user-images.githubusercontent.com/29311858/228106966-b202315c-b09b-474e-bf2d-210bb9d7221a.jpg)
![Works 2023-03-27 at 5 20 34 PM](https://user-images.githubusercontent.com/29311858/228106977-a2e1660e-c6c5-44d9-b4ee-a30dcd73b23d.jpg)

![Works 2023-03-27 at 5 20 57 PM](https://user-images.githubusercontent.com/29311858/228107028-dff108af-1e1e-46de-95e1-9b678275d66d.jpg)





</details>

**Comment by laritakr** [comment]
As of this morning, this completed normally. Staging for BL is extremely backed up, and the create relationship job has to run before the works are connected to the parent.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** The 20-page document successfully finished creating its derivatives overnight. This took so long only because staging is backed up.

tested on:
- https://mola.bl-staging.notch8.cloud/concern/articles/531123c9-daa2-4c1f-a0d1-dd7502899d31?locale=en
- [service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf](https://github.com/scientist-softserv/iiif_print/files/11084430/service-rbc-rbc0001-2015-2015gen56010-2015gen56010.pdf)


<details><summary>20-page PDF has its pages in order.</summary>

![Article naming convention ID 531123c9-daa2-4c1f-a0d1-dd7502899d31 Hyku 2023-03-28 at 11 37 40 AM](https://user-images.githubusercontent.com/29311858/228335902-431a65ec-04a1-4fb3-a295-a9ca975ee6dc.jpg)
</details>

**Comment by DiemBTran** [comment]
closing as this was a internal issue
