### ISSUE TITLE
Transform AF indexing properties to render_as

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#173]
# Summary

The m3 profile have indexing keys. The values need to get transformed in such a way that we can format it to match what hyrax expects. 

ref: https://github.com/scientist-softserv/iiif_print/blob/main/lib/iiif_print/configuration.rb#L72

```
resource_type: { render_as: :faceted },
```

# Acceptance Criteria

- [ ] If a property has indexing "facetable', that property should be a faceted link in the metadata pane.

# Screenshots or Video

# Testing Instructions

- Create two works
- Add one of the works as a child of the other
- Add metadata to `series` (since it is a faceted field)
- Navigate to the parent work and view the child work
- Observe that the field is a link and the link renders a faceted search

<details>
<summary>UTK instructions</summary>

- create an Attachment with an image file. `Rdf type: http://pcdm.org/use#IntermediateFile`
- Create a parent work without any image files. Add some subjects in the parent's metadata (subject is a facetable property according to their [m3](https://github.com/utkdigitalinitiatives/m3_profiles/blob/main/maps/utk.yml) profile). Save the parent work.
- Go the parent work's edit form > `Relationships` tab > `Other works in this work` > attach the child attachment from step 1. Save.
- now in the parent's work show page's UV, open the metadata pane and observe that the subjects are links
- click on the link and it should open a new tab with a facetted search for that term
</details>

# Notes

**Comment by ShanaLMoore** [comment]
This looks to be resolved with #154

**Comment by DiemBTran** [comment]
Paired with Kirk. Blocked for QA. Currently parent works are not showing thumbnails of child works. Because of this, parent works are not rendering their UV.

tested on:
- https://dc.utk-hyku-staging.notch8.cloud/concern/images/7ee462ca-20b1-43a4-a944-b23ace5d4321?locale=en

**Comment by ShanaLMoore** [comment]
#30 or gaining access to ESSI should unblock this.

**Comment by kirkkwang** [comment]
QA'd on staging with this work: https://dcadmin-test.dlib.indiana.edu/concern/paged_resources/zw12z528p?locale=en

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/19597776/230445390-5bb6b955-5439-4a0e-8fac-03110807128d.png">

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- parent work with child attached: https://dcadmin-test.dlib.indiana.edu/concern/images/qf85nb285?locale=en
- child work: https://dcadmin-test.dlib.indiana.edu/concern/images/5712m6524?locale=en

<details><summary>Parent work: cowboy has a child work: clown attached. In the Parent work's UV, facetable metadata field are hyperlinks. If you click a hyperlink, it navigates you to a search page with that facet as a query.</summary>

![Image parent work ID qf85nb285 Digital Collections 2023-04-12 at 3 11 58 PM](https://user-images.githubusercontent.com/29311858/231598142-c35dda30-08c7-427e-8382-cba385d77d24.jpg)
![Index Catalog Digital Collections 2023-04-12 at 3 12 27 PM](https://user-images.githubusercontent.com/29311858/231598154-89f477cd-6060-43d5-9601-2c855ee63a55.jpg)
</details>

**Comment by markpbaggett** [comment]
@jillpe this looks good to us.  We're going to bump it forward, but are curious if faceted fields will also be facets in search and not just links from the viewer / record.

**Comment by jillpe** [comment]
cc. @laritakr ^^
