### ISSUE TITLE
Auto UV Search

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#183]
# Summary

This work was previously done for LV ([PR](https://gitlab.com/notch8/louisville-hyku/-/commit/7c584b2fc58bd271db38d7ec5c2aba74a43c0ee2)), however it was removed per [this comment](https://gitlab.com/notch8/louisville-hyku/-/issues/122#note_994550119). ref (use Rob's credentials in gitlab, via 1password): https://gitlab.com/notch8/louisville-hyku/-/issues/97 and https://gitlab.com/notch8/louisville-hyku/-/commit/c9de6f38315ef36829c53aea68e1352dae67f6bd

Our clients (ADL specifically) has since asked for this feature to be added back. Otherwise, the user will have to type the same search twice. Once from the catalog search, then again in the UV search, so this work would enhance the user experience. 

# Acceptance Criteria

- [ ] When a user clicks on the catalog search results, it passes the search term as param into work (via url)
- [ ] If a search param exists, pre-populate the UV search with the term so that the user doesn't have to re-type it. 
- [ ] This feature should work with OCR and metadata searches.

# Screenshots or Video

# Testing Instructions
- [ ] Test using Essi
- [ ] You need a newly created work. Add metadata to this work for your testing.
  -  Sample file (an image with text; do not use a PDF): ![pure-bread](https://github.com/scientist-softserv/iiif_print/assets/29311858/26d3ea15-d62d-4b03-8e68-e40e56f19d5b)
- [ ] Wait for all the sidekiq jobs to clear
- [ ] OCR: 
  - [ ] From the catalog, search for an ocr term like "bread" (if using the sample file from above)
  - [ ] Once you click into the work, the term should populate and search in the UV without making the user type in the UV search bar. 
- [ ] METADATA: 
  - [ ] The same steps should apply here.

**NOTE** Searching for parent metadata will not succeed. A separate ESSI ticket has been created to address this. 

# Notes

The previous implentation had some missing logic. We need to consider adding conditionals: 

- if it's a match to the page and it's ocr, fill in teh search box. 
- if not, it's metadata: link to the page.  
- else, there are no matches don't link it to anything or display a no match error. 

Per Rob, If we get the original implementation, we can pair with him to add the conditionals.

**Comment by ShanaLMoore** [comment]
Reason for removal in LV per this [comment](https://gitlab.com/notch8/louisville-hyku/-/issues/122#note_994550119). 

this was discussed in the client meeting today.

> Explained that this is dependent on how they accessed the parent work. When doing a search query in the catalog search, that query is passed along to the parent work show page. A UV search is then automatically executed. The catalog search searches metadata and OCR, while the UV searches OCR only. In the event a word/phrase was found through a metadata search, it would then return the error they’re seeing if that word/phrase is not also in the OCR of the parent or children. This automatic UV search would not happen if no query were done (facet filtering is fine).

> For a better UX, they would like to remove the feature where a catalog search automatically queries in the uv viewer so that they don’t get the “no results were found” message

**Comment by ShanaLMoore** [comment]
To confirm pipeline failure in meeting with IU on Tuesday

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- work with OCR search query: https://dcadmin-test.dlib.indiana.edu/concern/images/5712m653d?locale=en&query=bread
- same work with metadata search query: https://dcadmin-test.dlib.indiana.edu/concern/images/5712m653d?locale=en&parent_query=alternative

<details><summary>OCR search from the catalog takes you to the query within the UV. Metadata search from the catalog points to the UV as well.</summary>

![Image Auto UV Search #183 ID 5712m653d Digital Collections 2023-05-10 at 12 26 04 PM](https://github.com/scientist-softserv/iiif_print/assets/29311858/5a6788b8-5991-4e92-a767-ed333a293c01)
![Image Auto UV Search #183 ID 5712m653d Digital Collections 2023-05-10 at 12 26 17 PM](https://github.com/scientist-softserv/iiif_print/assets/29311858/094a3a90-21e7-4451-9022-f67c73f90b03)
</details>

**Comment by jillpe** [comment]
closed - already present in essi
