### ISSUE TITLE
Audio and Video files should not get `TextExtractionDerivativeService` called

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#188]
# Summary
When uploading a Audio or Video file and `TextExtractionDerivativeService` is turned on, it will try to run that service which leads to an error.

# Acceptance Criteria

- [ ] As a user, I can upload an Audio or Video file and see my work in the viewer.

# Screenshots or Video

# Testing Instructions (test in BL)

- [x] Create time-based media Work. Add an audio file and create it
- [x] Observe that the audio plays in the viewer
- [x] Repeat for video file
 
# Notes

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- audio work: https://mola.bl-staging.notch8.cloud/concern/time_based_medias/8eb890c9-5cb8-4f2d-b1a7-18b021c67ecd?locale=en
- audio UV: https://mola.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://mola.bl-staging.notch8.cloud/concern/time_based_medias/8eb890c9-5cb8-4f2d-b1a7-18b021c67ecd/manifest&config=https://mola.bl-staging.notch8.cloud/uv/uv-config.json
- video: https://mola.bl-staging.notch8.cloud/concern/time_based_medias/2f49e3f3-69c7-4c2c-bfa4-9b2425045f24?locale=en
- video UV: https://mola.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://mola.bl-staging.notch8.cloud/concern/time_based_medias/2f49e3f3-69c7-4c2c-bfa4-9b2425045f24/manifest&config=https://mola.bl-staging.notch8.cloud/uv/uv-config.json

<details><summary> Audio and video files play in the UV</summary>

https://user-images.githubusercontent.com/29311858/228081810-e77c66e5-6bea-403b-bcfe-65d5d0092467.mp4
</details>

**Comment by DiemBTran** [comment]
Closing because this is an internal issue
