### ISSUE TITLE
Spike: Refactor code from Louisville in to iiif_print gem

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/iiif_print#19]
Treat this checklist as a spike. Do the investigation pieces and then move anything with substantial work it its own ticket. 

## Notes
ref #6 

## Acceptance
New tickets are made for any substantive work and the trivial stuff is done.

## Checklist

- [x] do we need to bring over config/initializers/iiif_manifest.rb from Louisville?
  - [x] looks like an override just to make sure all manifests have a `viewingHint` of `paged`, I don't think we want this
- [x] hydra derivative image decorator override should be pushed to image processors
  - [x] this [override](https://github.com/scientist-softserv/louisville-hyku/blob/main/lib/hydra/derivatives/processors/image_decorator.rb#L13-L22) has already been [made](https://github.com/samvera/hydra-derivatives/blob/main/lib/hydra/derivatives/processors/image.rb#L21-L30)
- [x] port lib/rdf/custom_is_child_term.rb from Louisville
  - [x] #10 
- [x] set_child_works.rake from lousiville
  - [x] #10 
- [x] do we need the modifications from `def manifest` and `def iiif_manifest_presenter` found in app/controllables/concerns/hyrax/works_controller_behavior.rb?
  - [x] `#manifest` was changed because of [this](https://github.com/scientist-softserv/louisville-hyku/commit/8d634a9e752c4111a6f5dc8ee63b9229f9823597) and it looks like `#iiif_manifest_presenter` is passing in `curation_concern_from_search_results` which is being [deprecated](https://github.com/samvera/hyku/blob/main/app/controllers/concerns/hyrax/works_controller_behavior.rb#L257-L263)
- [x] Louisville has a app/helpers/newspaper_works_helper.rb did a iiif_print version get created by the generator?
  - [x] yes
- [x] get all_decendant-file_sets and ancestor_ids from app/indexers/app_index.rb and put it in iiif_print indexer mixin
  - [x] #10 
- [x] get app/indexers/hyrax/file_set_indexer and put it in a iiif_print mixin
  - [x] #10 
- [x] port app/models/concerns/set_child_flag to iiif_print, include in work types
  - [x] #10
- [ ] #26
  - [ ] doesn't look like it
- [ ] #27
  - [ ] seems like it would be useful, not sure where else to put it if not in the helper
- [ ] #28
  - [ ] i think the more the gem can handle the better
- [ ] #29
  - [ ] Alisha said these came from [hyrax 3 ](https://github.com/samvera/hyrax/tree/main/app/views/hyrax/file_sets/media_display)
- [ ] #30
- [ ] #31
- [ ] #32
- [ ] #33
- [ ] #34
- [ ] #35
- [ ] #36
- [ ] #37
- [ ] #38

**Comment by ShanaLMoore** [comment]
Are any of these points occurring from the generator? What is the diff between that and LV?

**Comment by ShanaLMoore** [comment]
video demo: https://assaydepot.slack.com/archives/G0313NK5NMA/p1670518821493579

**Comment by jillpe** [comment]
Refer to #8

**Comment by kirkkwang** [comment]
answered questions the best i could and created tickets for all other action items

**Comment by ShanaLMoore** [comment]
Kirk created tickets so we can close this spike now.
