### ISSUE TITLE
should the gem auto create app/views/hyrax/base/iiif_viewers or is that an app concern?

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#28]
# Summary

# Acceptance Criteria

- [ ] The application that IIIF Print is installed on should have the Hyrax 3+ implementation of universal viewer

# Screenshots or Video

# Testing Instructions

- [ ] navigate to a work show page that has an image
- [ ] confirm Universal Viewer loads

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by kirkkwang** [comment]
need, should be a concern of the gem

did the view partial change in hyrax 3? 4?

**Comment by ShanaLMoore** [comment]
put the view partial in the gem
