### ISSUE TITLE
Spike: are all the changes in app/views/hyrax/file_sets made by the generator?

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#29]
# Summary

# Acceptance Criteria

- [ ] Determine if the generator made changes to `app/views/hyrax/file_sets`
- [ ] IF SO...
- [ ] IF NOT...

DONE looks like...

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by kirkkwang** [comment]
Alisha said these came from [hyrax 3](https://github.com/samvera/hyrax/tree/main/app/views/hyrax/file_sets/media_display)

**Comment by kirkkwang** [comment]
check if exists in hyku

**Comment by kirkkwang** [comment]
i ran the generator and saw a lot of tiny differences that didn’t seem like it was noteworthy, but this one stuck out to me, https://github.com/scientist-softserv/louisville-hyku/blob/main/app/controllers/catalog_controller.rb#L484-L503
this whole method is missing from the generator, does it look like something we want?

**Comment by jillpe** [comment]
closed - confirmed @laritakr we can combine this with #40
