### ISSUE TITLE
port over set_parent_thumbnail.rake from LV

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#30]
https://github.com/scientist-softserv/louisville-hyku/blob/main/lib/tasks/set_parent_thumbnail.rake

**Comment by ShanaLMoore** [comment]
done ✅ But potentially not needed anymore due to LaRita's work #11

**Comment by ShanaLMoore** [comment]
PR to remove take task: https://github.com/scientist-softserv/iiif_print/pull/69
