### ISSUE TITLE
Spike: verify that running the generators gets you all the needed adjustments for iiif search found in lousiville app/controller/catalog_controller.rb

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#33]
# Summary

verify that running the generators gets you all the needed adjustments for iiif search found in lousiville app/controller/catalog_controller.rb

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Implementation suggestion: 

run the generator from iiif print main on a clean hyku and then compare the [CatalogController](https://github.com/scientist-softserv/louisville-hyku/blob/main/app/controllers/catalog_controller.rb) of each spot and take note of the diff.

**Comment by kirkkwang** [comment]
i ran the generator and saw a lot of tiny differences that didn’t seem like it was noteworthy, but this one stuck out to me, https://github.com/scientist-softserv/louisville-hyku/blob/main/app/controllers/catalog_controller.rb#L484-L503
this whole method is missing from the generator, does it look like something we want?

**Comment by jillpe** [comment]
closed - confirmed by @laritakr we can combine this with #40
