### ISSUE TITLE
Spike: add derived_members and derived_files override to app/presenters/work_show_presenter

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#34]
- [ ] https://github.com/scientist-softserv/louisville-hyku/blob/42a0fc837fd9ef4832a9741731672200e0097305/app/presenters/hyku/work_show_presenter.rb#L65-L73 <- methods are defined in LV but aren't being used 🤔 

Attempt to answer why these methods exist. Is it necessary to keep or transfer over to iiif_print? 

- [ ] is it related to [this](https://github.com/scientist-softserv/louisville-hyku/blob/42a0fc837fd9ef4832a9741731672200e0097305/app/models/file_set.rb#L5)?

## Next Steps
Close this ticket if these methods are not required, or after creating a new ticket that'll implements them in iiif_print.

**Comment by ShanaLMoore** [comment]
LV pulled [this](https://github.com/scientist-softserv/nnp/blob/main/app/presenters/hyku/work_show_presenter.rb#L9-L18) in from NNP. And yes, it is related to [is_derived_ssi](https://github.com/scientist-softserv/nnp/search?q=is_derived_ssi).

[commit](https://github.com/scientist-softserv/nnp/commit/64d963db021fecb43a5d59be0566b34cf5ea2740): "decide to show bookreader or not"

**Comment by ShanaLMoore** [comment]
nnp BookReader: https://github.com/internetarchive/bookreader

**Comment by ShanaLMoore** [comment]
![Image](https://user-images.githubusercontent.com/10081604/211359467-833f88b2-33f3-404b-a67b-68f74f1d5e88.png)



![Image](https://user-images.githubusercontent.com/10081604/211360609-051d9933-efaa-4fd9-97d7-49a51ec6f62a.png)

**Comment by ShanaLMoore** [comment]
Context: 

NNP and LV has a process to define certain files sets are being derivatives of other file
sets.

 This needs to decided after LaRita's work is done. We probably won't have to bring over the is_derived however the implementation will be determined after LaRita's work. #11

**Comment by ShanaLMoore** [comment]
created ticket #[297](https://github.com/scientist-softserv/utk-hyku/issues/297)
