### ISSUE TITLE
:bug: Persist derivatives as Hyrax::FileMetadata objects for Valkyrie

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/iiif_print#350]
# Summary

# Acceptance Criteria

- [ ] Files should have derivatives when Iiif print splits in a valkyrie app

# Screenshots or Video

# Testing Instructions

On [Hyku](https://demo.hyku-demo.notch8.cloud/)
manually create a work. attach a multi page pdf to it. 
after the jobs complete and the pdfs have split, ensure the files have derivative attached. 

ie: 

![Image](https://github.com/scientist-softserv/iiif_print/assets/10081604/76ae108e-aa72-4ae0-a3b5-79084bad62d0)

https://github.com/scientist-softserv/iiif_print/issues/350#issuecomment-2168222532
# Notes

**Comment by ShanaLMoore** [comment]
remote urls will not work with iiif print at this point

**Comment by jillpe** [comment]
Blocked: Waiting to be updated in hyku

**Comment by laritakr** [comment]
https://github.com/samvera/hyku/pull/2210

**Comment by ShanaLMoore** [comment]
@laritakr How can this be tested? Should we just close it?

**Comment by laritakr** [comment]
> @laritakr How can this be tested? Should we just close it?

The only way is to go into the server and verify that each fileset has multiple Hyrax::Metadata objects, for the original file, thumbnail, and all other derivatives. Other than that, it's just verifying that the full text gets indexed and the search stuff works... that's a pretty good sign that the derivatives are where they need to be.

**Comment by ShanaLMoore** [comment]
Test in hyku

**Comment by jillpe** [comment]
Testing:
- Verify the fileset dropdown has 'download...'

**Comment by jillpe** [comment]
SoftServ QA: ✅ 



![Image](https://github.com/scientist-softserv/iiif_print/assets/84697174/00b602db-1962-4027-8cc0-73f663a90c0d)
