### ISSUE TITLE
Louisville app/presenters/hyrax/work_show_presenter_decorator has several iiif / nesting items in it

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#36]
ref: https://github.com/scientist-softserv/louisville-hyku/blob/42a0fc837fd9ef4832a9741731672200e0097305/app/presenters/hyrax/work_show_presenter_decorator.rb

Compare to hyrax/hyku's version to spot the differences.

parent/child relationships should display properly.

[This](https://github.com/scientist-softserv/louisville-hyku/blob/main/app/views/hyrax/base/_items.html.erb#L19) view file uses [this](https://github.com/scientist-softserv/louisville-hyku/blob/main/app/presenters/hyrax/work_show_presenter_decorator.rb#L38) method which will probably need to be moved over as well

**Comment by kirkkwang** [comment]
Hyku's version inherits from Hyrax's version, no overrides spotted

**Comment by jillpe** [comment]
This can be broken down into additional tickets:

1. allow for configuration of sort order
2. allow for configuration of filtering of members
3. good recommended default

**Comment by ShanaLMoore** [comment]
This ticket may not be needed. By default, LaRita's work #11 should handle sorting ordered_members, which is how the items should get displayed. 

We may consider offering a configuration for sort, so that the client can choose what they want instead.

**Comment by ShanaLMoore** [comment]
cc @kirkkwang Is this ticket about giving users to configure a way for items to get presented in the UV?

**Comment by kirkkwang** [comment]
I believe so, that's the [item partial ](https://github.com/scientist-softserv/louisville-hyku/blob/main/app/views/hyrax/base/_items.html.erb)in LV is supposed to do.

It also deals with showing the UV even if the parent image doesn't have a fileset.  [This file](https://github.com/scientist-softserv/louisville-hyku/blob/main/app/views/hyrax/base/_representative_media.html.erb) from LV would also need to be added to make it work.

related issue https://github.com/scientist-softserv/iiif_print/issues/76

**Comment by jillpe** [comment]
closed - duplicate of #76
