### ISSUE TITLE
port app/services/hyrax/manifest_builder_service_decorator to the iiif_print gem

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#37]
# Summary
File now exists, but needs to be made functional. Specifically for IIIF manifest 2 and 3

ref: https://github.com/scientist-softserv/iiif_print/blob/main/lib/generators/iiif_print/templates/manifest_builder_service_decorator.rb

Indiana is open to upgrading their manifest. 

Heads Up: Indiana has a configuration to pull in the metadata into the manifest. This will need some work, and we also may need to consider how it will work with AllinsonFlex.

The end goal is for the UV to display the way that LV has it.

---

# Acceptance Criteria

- [ ] When looking at the works show page, works with metadata should display their metadata in the Universal Viewer right side panel

# Screenshots or Video

# Testing Instructions
https://demo.hyku-iiif.notch8.cloud/
- [ ] Create a work with some metadata properties
- [ ] Navigate to its show page
- [ ] Open the right side panel and confirm the metadata shows up

# Notes

- AllinsonFlex handling will need to be apart of a different ticket [#298](https://github.com/scientist-softserv/utk-hyku/issues/298)
- Essi uses [this](https://github.com/IU-Libraries-Joint-Development/essi/blob/main/config/initializers/hyrax.rb#L192) implementation where it seems there is select metadata to be displayed
- Essi's implementation does not support facetable links fro the UV metadata panel
- Essi uses IIIF Presentation Manifest V2 which is the Hyrax 2x default, while UTK (on Hyrax 3x) uses IIIF Presentation Manifest V3

**Comment by ShanaLMoore** [comment]
QA RESULTS: 

On staging, when creating a manual work, we can see the file in the UV. However, when you add a child manually, the parent's UV no longer displays anything. When you click into the child, we can see its file in the UV. 

![image](https://user-images.githubusercontent.com/10081604/213330664-651c82d4-e46f-4c88-91ef-a01cc2fd12b3.png)
![image](https://user-images.githubusercontent.com/10081604/213330692-c31eab73-34f9-4e06-9a38-869f11ff46ee.png)
![image](https://user-images.githubusercontent.com/10081604/213330714-f138dbaa-5550-4e9a-8a38-f2a2e6953d6c.png)

**Comment by ShanaLMoore** [comment]
This passes QA: 

On staging, I manually created a parent and child work. I can see the child work and its metadata, from the parent's UV. 

![Image](https://user-images.githubusercontent.com/10081604/214100056-88fc28c3-e8d1-4212-b7d6-bbddfb22c23f.png)


However, I will create a separate spin-off ticket to handle the following edge case cc @kirkkwang A UV should still render if the parent doesn't have a fileset: 



![Image](https://user-images.githubusercontent.com/10081604/214100223-5d9b51df-2bb3-4d92-a5c6-fc0c77feca64.png)
