### ISSUE TITLE
apply fix from app/services/newspaper_works/data/work_files_decorator to the iiif_print gem

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#38]
ref LV: https://github.com/scientist-softserv/louisville-hyku/blob/main/app/services/newspaper_works/data/work_files_decorator.rb

compare to iiif_print: https://github.com/scientist-softserv/iiif_print/search?q=commit_assigned

redefine method in iiif_print to match LV

**Comment by ShanaLMoore** [comment]
TODO: Trace down the commit of the project that pulled this fix in, to try to figure out what this fixed. please take notes on findings.

**Comment by ShanaLMoore** [comment]
> TODO: Trace down the commit of the project that pulled this fix in, to try to figure out what this fixed. please take notes on findings.

LV: https://github.com/scientist-softserv/louisville-hyku/blob/42a0fc837fd9ef4832a9741731672200e0097305/app/services/newspaper_works/data/work_files_decorator.rb

# Overrides newspaper_works 1.0.1 to allow update or create based on work state

**Comment by kirkkwang** [comment]
There are specs to test the paths of this fix
