### ISSUE TITLE
Generator check / Install IiifPrint into Hyku

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#40]
**THIS SHOULD BE TESTED LOCALLY**

This ticket is meant to be done towards the end of the iiif_print epic

We want to confirm that the generator does everything it needs to, when installing iiif_print onto a hyrax/hyku project.

- [ ] Test generator by installing iiifprint on hyku main
- [ ] We ultimately will be merging iiif_print into hyku so this ticket can be treated as a 2 for 1. (as in tested generator locally and confirm all is good, but also make a PR out of it).

## NOTES: 

#121 Generator Refactor

# Screenshots / Video

Tested on https://demo.hyku-iiif.notch8.cloud

Sample Files: 

# Expected Behavior

User should be able to perform all that's listed in the [features list's user story tab](https://docs.google.com/spreadsheets/d/1V3DoknWcmGQwc5StU1zBQxpGRQ7ttctwxXpbfxJvtsw/edit#gid=882540390)

## Testing Instructions

A user should perform all that is defined in the user story tab of the [Features List](https://docs.google.com/spreadsheets/d/1V3DoknWcmGQwc5StU1zBQxpGRQ7ttctwxXpbfxJvtsw/edit#gid=882540390)

**Comment by jillpe** [comment]
- [ ] did the generator create the app/helpers/hyrax/iiif_helper.rb file?
- [ ] are all the changes

**Comment by jillpe** [comment]
To Do:
- [ ] verify that running the generators gets you all the needed adjustments for iiif search found in lousiville app/controller/catalog_controller.rb
- [ ] Determine if the generator made changes to app/views/hyrax/file_sets
 IF SO...
 IF NOT...

Notes:
Implementation suggestion:

run the generator from iiif print main on a clean hyku and then compare the [CatalogController](https://github.com/scientist-softserv/louisville-hyku/blob/main/app/controllers/catalog_controller.rb) of each spot and take note of the diff.

i ran the generator and saw a lot of tiny differences that didn’t seem like it was noteworthy, but this one stuck out to me, https://github.com/scientist-softserv/louisville-hyku/blob/main/app/controllers/catalog_controller.rb#L484-L503
this whole method is missing from the generator, does it look like something we want?



Alisha said these came from [hyrax 3](https://github.com/samvera/hyrax/tree/main/app/views/hyrax/file_sets/media_display)
https://github.com/scientist-softserv/louisville-hyku/commit/f8d98d845883258e43102a24af5933503ad5d431

check if exists in hyku

check if they are apart of Lea Ann's plan for PALS, if not make a ticket to add

**Comment by jillpe** [comment]
Referenc #33 and #29

**Comment by ShanaLMoore** [comment]
cut a new hyku branch w a fresh install after Jeremy's #121 , and test

**Comment by jillpe** [comment]
Blocked

**Comment by ShanaLMoore** [comment]
Rob is working on Hyku https://github.com/samvera/hyku/pull/1925

**Comment by ShanaLMoore** [comment]
Resolved pipeline issues and verified basic tests on https://demo.hyku-iiif.notch8.cloud/dashboard/my/works?locale=en

**Comment by ShanaLMoore** [comment]
I'll create a configuration ticket to wrap up this work. Then it can be QA'd.
