### ISSUE TITLE
Write up a test plan

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/iiif_print#65]
# Summary
Ask Diem to share template for test plan
Ask Rob to review test plan

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by ShanaLMoore** [comment]
This may not be needed afterall.

**Comment by ShanaLMoore** [comment]
https://docs.google.com/spreadsheets/d/1V3DoknWcmGQwc5StU1zBQxpGRQ7ttctwxXpbfxJvtsw/edit#gid=0
