### ISSUE TITLE
Write up features and configurability

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/iiif_print#66]
Write up what this gem should do, its features, and what's configurable.

**Comment by ShanaLMoore** [comment]
Created a [features list section](https://github.com/scientist-softserv/iiif_print/wiki/Features-List) of the wiki, copied from NewspaperWorks for starters.

My plan is to comb through this, as well as our PRs. Additionally, I will add a section about which features are configurable.

**Comment by ShanaLMoore** [comment]
Team review meeting scheduled for Feb 1st, Wednesday at 9AM PST.

**Comment by ShanaLMoore** [comment]
Team V mobbed on the features list. Next step is to have @jillpe @crisr15 and @orangewolf review it.

**Comment by jillpe** [comment]
Closed in sprint 2/6/2023
