### ISSUE TITLE
`MetadataBuilderService` should handle version 3 manifests

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#71]
# Summary

The `MetadataBuilderService` should also handle IIIF version 3 manifests as well.

# Acceptance Criteria

- [ ] Metadata is shown for items on a version 3 manifest

# Screenshots or Video

# Testing Instructions (test w BL)

- [x] Navigate to a work has an image that you can see in the Universal Viewer
- [x] Open the right side panel and confirm there is metadata
- [x] in the URL append /manifest.json (delete any locale stuff)
- [x] confirm in the `context` that is is a `presentation/3/context.json`

**Comment by jillpe** [comment]
depends on #225

**Comment by kirkkwang** [comment]
can be tested on BL

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot and recording.

tested on:
- work: https://mola.bl-staging.notch8.cloud/concern/images/56031ac2-0801-48b6-807c-d9a78d712319?locale=en
- work's uv: https://mola.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://mola.bl-staging.notch8.cloud/concern/images/56031ac2-0801-48b6-807c-d9a78d712319/manifest&config=https://mola.bl-staging.notch8.cloud/uv/uv-config.json 
- work's manifest.json: https://mola.bl-staging.notch8.cloud/concern/images/56031ac2-0801-48b6-807c-d9a78d712319/manifest.json

<details><summary>The UV has metadata and the manifest.json's context contains "presentation/3/context.json"</summary>

![mola bl-staging notch8 clouduvuv html#manifest=mola bl-staging notch8 cloudconcernimages56031ac2-0801-48b6-807c-d9a78d712319manifest config=mola bl-staging notch8 clouduvuv-config jsonmanifest json 2023-03-27 at 1 49 33 PM](https://user-images.githubusercontent.com/29311858/228063516-83078473-567c-433f-b9e3-31ab6ba6dd37.jpg)
![mola bl-staging notch8 cloudconcernimages56031ac2-0801-48b6-807c-d9a78d712319manifest json 2023-03-27 at 12 54 09 PM](https://user-images.githubusercontent.com/29311858/228063536-c5ed3695-8a3b-4e83-9763-edbdd97db108.jpg)
</details>

**Comment by DiemBTran** [comment]
Client QA not necessary because this was an internal issue
