### ISSUE TITLE
`MetadataBuilderService` should handle properties generated by AllinsonFlex

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#72]
# Summary
The MetadataBuilderService should also handle metadata properties that were generated from AllinsonFlex in both version 2 and version 3 manifests.

# Acceptance Criteria
- [ ] Metadata is shown for items on an application with AllinsonFlex installed.

# Screenshots or Video

# Testing Instructions (UTK staging)
In an application installed with AllinsonFlex
- [ ] Navigate to a work with an image that shows in the Universal Viewer
- [ ] Check that the metadata is showing in the right panel
  - [ ] Add a few more metadata to other properties to double check it works

**Comment by kirkkwang** [comment]
test on UTK

**Comment by kirkkwang** [comment]
QA with https://github.com/scientist-softserv/iiif_print/issues/173

**Comment by DiemBTran** [comment]
Paired with Kirk. Blocked for QA. Currently parent works are not showing thumbnails of child works. Because of this, parent works are not rendering their UV.

tested on:
- https://dc.utk-hyku-staging.notch8.cloud/concern/images/7ee462ca-20b1-43a4-a944-b23ace5d4321?locale=en

**Comment by ShanaLMoore** [comment]
#30 or gaining access to ESSI should unblock this.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- work with UV in a tenant that has AllinsonFlex installed: https://dc.utk-hyku-staging.notch8.cloud/concern/compound_objects/a533ac85-c06e-4717-872c-a4ae85016fc0?locale=en

<details><summary>work's metadata shows in UV before and after edit</summary>

![Compound Object i192  5  Base Manifest IIIF Recipe - Compound Object ID a533ac85-c06e-4717-872c-a4ae85016fc0 Hyku 2023-04-04 at 12 04 56 PM](https://user-images.githubusercontent.com/29311858/229895230-2447031c-a2be-441f-ba9e-e67a7369cfc1.jpg)
![Compound Object i192  5  Base Manifest IIIF Recipe - Compound Object ID a533ac85-c06e-4717-872c-a4ae85016fc0 Hyku 2023-04-04 at 11 53 33 AM](https://user-images.githubusercontent.com/29311858/229895234-33ba4b99-93bf-4854-a245-07a296a4e8cb.jpg)
</details>
