### ISSUE TITLE
Parent UV doesn't render when it doesn't have a fileset

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#76]
# Summary
spin off ticket from i37

The parent UV does not render when it doesn't have filesets. It should still render if it has children. 

# Acceptance Criteria

- [ ] If a parent work has no files && has children (with filesets), it should still render in the parent's UV.

# Screenshots or Video

![image](https://user-images.githubusercontent.com/10081604/214104285-34419def-b978-4f60-b1ce-2b30b8386d9e.png)

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by ShanaLMoore** [comment]
I did a little bit of research and I believe something in [this](https://github.com/samvera/hyrax/blob/main/app/presenters/hyrax/work_show_presenter.rb#L65-L71) method needs to change. I don't have time to focus on this so I'm releasing it back to the team.

**Comment by jillpe** [comment]
Reference #36

**Comment by ShanaLMoore** [comment]
This PASSES QA: 

Link to Importer: https://demo.hyku-iiif.notch8.cloud/importers/16?locale=en

Link to parent w no fileset, but w a child: https://demo.hyku-iiif.notch8.cloud/concern/images/c0c69923-34dd-48b4-aad5-52e00a022bee?locale=en



![Image](https://user-images.githubusercontent.com/10081604/216653750-cac0d661-9bfa-4087-bec5-bf0e963350f0.png)



sample file: 

[basic.zip](https://github.com/scientist-softserv/iiif_print/files/10580678/basic.zip)



![Image](https://user-images.githubusercontent.com/10081604/216653869-153e93c5-86d2-4e2d-a8ba-b64180b3862a.png)
