### ISSUE TITLE
🎁 Make the UV display records in the same order as the items section of the show page.

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/iiif_print#79]
# Summary

The order of the works that are displayed in the items partial in the work show page does not always match the way the UV's display order.

# Acceptance Criteria

- [ ] Both UV and items partial show the same order

# Screenshots or Video

# Testing Instructions

- [ ] A dev should set the `sort_iiif_manifest_canvases_by` to `:date_created` in the configuration
- [ ] Deploy the branch
- [ ] The tester should import this CSV via Bulkrax [sw.csv](https://github.com/scientist-softserv/iiif_print/files/10492884/sw.csv)
- [ ] Confirm that the items at the bottom of the show page displays in the same order as the UV

**Comment by jillpe** [comment]
This work was done in lv

**Comment by jeremyf** [comment]
This needs further discussion as:

- Hyrax has ordered members, which is likely something we should consider as the canonical sort order.
- When Bulkrax fails for one member, and we retry, we may not be adjusting the ordered members.
- The UI should provide a way to re-order the items.
- Likewise, we may need to recommend a round-trip import export with ordering

**Comment by ShanaLMoore** [comment]
For essi, we need to consider their file manager. this is a tool that allows a user to manually move and re order their files. It saves it to ordered_members. so simple changing the display of things will override this feature, which is likely undesired.

**Comment by jillpe** [comment]
closed no longer relevant because we are sorting UV manifest on ordered members
