### ISSUE TITLE
Fix OCR Catalog Search

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/iiif_print#88]
# Summary

[ Is full or all text getting indexed](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/156/diffs#256bdc48984dcae0d6ebd2deb88b77e04c0234df)? etc...

# Acceptance Criteria

- [x] When a user performs a catalog search for OCR, the parent should return. ref: https://gitlab.com/notch8/louisville-hyku/-/merge_requests/137#a79adb1024bf4a71a325bf3ac94b212477013dae

# Screenshots or Video

# Testing Instructions
Deploy i87-ocr-search to hyku-iiif (hyku branch) ✅ visit: demo.hyku-iiif.notch8.cloud/
1. Create a work. Upload an image that has text. OCR should run. Confirm that json coordinates are created as its derivatives. Confirm that a user can search for the text in the UV, and find a match.
2. Create a work. Attach a child. Confirm that a user can visit the parent's UV, search for the child's metadata and find a match.
3. A user should able be able to catalog search the child metadata and have its parent return
4. A user should be able to catalog search the child's ocr term and have its parent return

# Notes

The commits in Louisville that worked towards this are:

- https://github.com/scientist-softserv/louisville-hyku/commit/128a9ef — i149 - fix timing issue that cause child ocr search bug Shana Moore, (2022-09-21)
- https://github.com/scientist-softserv/louisville-hyku/commit/50489ac — 90-ocr-highlighting Alisha Evans, (2022-05-12)
- https://github.com/scientist-softserv/louisville-hyku/commit/211e888 — i19 - pull in uv configs from nnp to enable ocr search Shana, (2022-01-26)

maybe helpful refs: 
1. https://gitlab.com/notch8/louisville-hyku/-/merge_requests?scope=all&state=merged&search=ocr

If things aren't working, try... 

`ActiveFedora::Base.reindex_everything`

**Comment by ShanaLMoore** [comment]
to get this working, we needed to add and set advanced_parse to false

![Image](https://user-images.githubusercontent.com/10081604/214947481-ed95e76c-a332-482f-bcc3-78ac9d9a7c3a.png)

**Comment by ShanaLMoore** [comment]
Yes, the deploy failed. I will move this back to deploy to staging.

**Comment by DeonFranklin** [comment]
This ticket passes Soft Serv QA

![Image](https://user-images.githubusercontent.com/95306716/219213594-081a5888-4e9d-41ea-bcaf-32f868d2b9ba.png)
![Image](https://user-images.githubusercontent.com/95306716/219213596-07adae2f-fb8f-4553-b19d-1d4ef20ba993.png)
![Image](https://user-images.githubusercontent.com/95306716/219213595-d110b68a-0fca-4fd5-b461-63d9743f4709.png)
![Image](https://user-images.githubusercontent.com/95306716/219213723-98c7085a-93f9-4d05-bc9c-00c74a5c93df.png)
